### ISSUE TITLE
Deploying SST site on Docker via Assumed Role is resulting in deployment failure

### ISSUE THREAD

**Issue by itsfaraaz** [anomalyco/sst#3969]
I am attempting to deploy via SST on a Docker Linux container. I have installed AWS CLI on the container. When I run the command `aws sts get-caller-identity` I get:

`{ "UserId": "AIDAVG7TGW6NUZQL4XI5L", "Account": "358602946459", "Arn": "arn:aws:iam::358602946459:user/docker" }`

This tells me that the Docker container is able to successfully access AWS account ID 358602946459.

What I am attempting to do here is make an SST.dev deployment. I have installed the SST CLI as well. I believe SST v3 under the hood uses Pulumi. My sst config file is this:

```
// <reference path="./.sst/platform/config.d.ts" />
export default $config({
  app() {
    return {
      name: "faraazxyz-dks94",
      removal: "remove",
      home: "aws",
      providers: {
        aws: {
          region: "us-east-1",
          allowedAccountIds: ["203918846642"],
          assumeRole: {
            roleArn: "arn:aws:iam::203918846642:role/<redacted>",
          },
          accessKey: process.env.AWS_ACCESS_KEY_ID,
          secretKey: process.env.AWS_SECRET_ACCESS_KEY,
        }
      }
    };
  },
  async run() {
    new sst.aws.Nextjs("faraazxyz-dks94", {
      
    domain: {
      name: "faraaz.xyz",
      redirects: ["www.faraaz.xyz"],
    
      aliases: ["faraazxyz-dks94.visioner.cloud","www.faraazxyz-dks94.visioner.cloud"]
    }
    });
  },
});
```

The `accessKey` and `secretKey` are for account ID 358602946459.

What I want to do is that I have given this Docker container access to the account ID 358602946459 (evident by the AWS CLI command above). What I want to do is deploy the site's resource to a different AWS account, with ID 203918846642. I have created a role that the main AWS account can assume to do this. I have verified that 358602946459 is able to assume the role in 203918846642 via the CLI:

```
# aws sts assume-role --role-arn arn:aws:iam::203918846642:role/<redacted> --role-session-name TestSession
{
    "Credentials": {
        "AccessKeyId": "<redcated>",
        "SecretAccessKey": "<redacted>",
        "SessionToken": "<redcated>",
        "Expiration": "2024-10-13T05:17:42+00:00"
    },
    "AssumedRoleUser": {
        "AssumedRoleId": "<redcated>:TestSession",
        "Arn": "arn:aws:sts::203918846642:assumed-role/<redacted>/TestSession"
    }
}
```

When I run `sst deploy --stage production` on the Docker container, i then get this error:

```
|  Updated     faraazxyz-dks94 sst:aws:Nextjs → faraazxyz-dks94Build sst:Run (51.6s)
panic: interface conversion: interface {} is string, not resource.PropertyMap
goroutine 42 [running]:
github.com/pulumi/pulumi/sdk/v3/go/common/resource.PropertyValue.ObjectValue(...)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.133.0/go/common/resource/properties.go:462
github.com/pulumi/pulumi-aws/provider/v6.validateCredentials(0xc0092b4600, {0x19b6acde?, 0x0?})
        /home/runner/work/pulumi-aws/pulumi-aws/provider/resources.go:624 +0x13ca
github.com/pulumi/pulumi-aws/provider/v6.ProviderFromMeta.preConfigureCallback.func26(0xc0092b4600, {0x1bcf1ec0, 0xc003321548})
        /home/runner/work/pulumi-aws/pulumi-aws/provider/resources.go:790 +0xff
github.com/pulumi/pulumi-terraform-bridge/pf/tfbridge.(provider).runPreConfigureCallback(0xc007c59188, {0x1bfaeb38?, 0xc00917ef60?}, 0xc0092b4600)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/pf@v0.44.1/tfbridge/provider_checkconfig.go:131 +0x104
github.com/pulumi/pulumi-terraform-bridge/pf/tfbridge.(provider).CheckConfigWithContext(0xc007c59188, {0x1bfaeb38?, 0xc00913f920?}, {0xc00844af00, 0x57}, 0x2c710e0?, 0xc00917ea20, 0x50?)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/pf@v0.44.1/tfbridge/provider_checkconfig.go:84 +0x68e
github.com/pulumi/pulumi-terraform-bridge/pf/internal/configencoding.(provider[...]).CheckConfigWithContext(0xc00433a8f0, {0x1bfaeb38?, 0xc00913f920}, {0xc00844af00, 0x57}, 0xc00913fb00, 0xc00913fb30, 0x1)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/pf@v0.44.1/internal/configencoding/provider.go:74 +0xf5
github.com/pulumi/pulumi-terraform-bridge/pf/internal/plugin.(providerServer).CheckConfig(0xc00913e090, {0x1bfaeb38, 0xc00913f920}, 0xc00914a200)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/pf@v0.44.1/internal/plugin/provider_server.go:227 +0x203
github.com/pulumi/pulumi-terraform-bridge/x/muxer.(*muxer).CheckConfig.func1()
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/x/muxer@v0.0.8/muxer.go:127 +0x6f
github.com/pulumi/pulumi-terraform-bridge/x/muxer.asyncJoin[...].func1()
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/x/muxer@v0.0.8/muxer.go:595 +0x42
created by github.com/pulumi/pulumi-terraform-bridge/x/muxer.asyncJoin[...] in goroutine 40
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/x/muxer@v0.0.8/muxer.go:594 +0x79
|  Error       AwsProvider sst:us-east-1
|  rpc error: code = Unavailable desc = error reading from server: EOF
✕  Failed    
   AwsProvider sst:us-east-1
   rpc error: code = Unavailable desc = error reading from server: EOF
```

I am unsure where this could be coming from as the error message is ambiguous. Any help is appreciated here.

**Comment by jabali2004** [comment]
Could that be related to https://github.com/pulumi/pulumi-aws/issues/2411?

I'm facing that issue right now. But in my case, I'm relying on the aws provider directly. After the role is created, it supposedly needs a couple of seconds to propagate. But the provider reports the iam role as successfully created.
