### ISSUE TITLE
Pulumi Interrupted Error using VPC on local

### ISSUE THREAD

**Issue by rijvirajib** [anomalyco/sst#5070]
I brought it up in Discord but now I am having the same issues on another machine with a fresh pull of my repo, first time `npx sst dev` works but subsequent times, let's say I restart the computer, it fails. Removing the VPC (and RDS) resolves the issue and I can go back to running `sst dev` without issues. The console only shows INTERRUPTED and `--mode basic` stalls and never goes past `level=INFO msg="got auth"` which happens twice.

Deleting .sst and ~/....config/sst does not fix it. Wiping node_modules and running sst also does not fix it. Changing stage fixes it for the first time and after things are deployed, the issues continue again. I have changed devices thinking it was something with my local machine but duplicating on another OS. Same issue on Windows WSL and MacOS.

Attached is my report.zip. Any ideas in fixing this would be appreciated. It's blocking since I have to change stages, re-do my migrations, re-do my seeds, I would like to avoid this.

```
    const vpc = new sst.aws.Vpc('VPC', {
      nat: 'ec2',
      bastion: true
    });

    const rds = new sst.aws.Postgres('RDS', {
      database: 'trader_dev',
      // username: pgUsernameSecret.value,
      password: pgPasswordSecret.value,
      storage: '100 GB',
      vpc: vpc,
      proxy: true,
    });
```
pulumi.log (nothing else):
```
Updating (rijvirajib):
```

snippet from sst.log
```
time=2024-11-14T23:27:36.379-05:00 level=ERROR msg="stack run failed" error="failed to run update: exit status 1\ncode: 1\nstdout: Updating (rijvirajib):\n\nstderr: ================================================================================\nThe Pulumi CLI encountered a fatal error. This is a bug!\nWe would appreciate a report: https://github.com/pulumi/pulumi/issues/\nPlease provide all of the text below in your report.\n================================================================================\nPulumi Version:   v3.136.1\nGo Version:       go1.23.2\nGo Compiler:      gc\nArchitecture:     amd64\nOperating System: darwin\nPanic:            runtime error: invalid memory address or nil pointer dereference\n\ngoroutine 1 [running]:\nruntime/debug.Stack()\n\t/opt/hostedtoolcache/go/1.23.2/x64/src/runtime/debug/stack.go:26 +0x5e\nmain.panicHandler(0xc001f3ff27)\n\t/home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/main.go:34 +0x45\npanic({0x541c460?, 0x6dca0f0?})\n\t/opt/hostedtoolcache/go/1.23.2/x64/src/runtime/panic.go:785 +0x132\ngithub.com/pulumi/pulumi/pkg/v3/backend/diy.(*diyBackend).getTarget(0xc001f81cb0, {0x584eb08, 0x6e8eda0}, {0x582a200, 0x6e8eda0}, 0xc001f8fe80, 0xc001f5c210, {0x4e797d98, 0x6e8eda0})\n\t/home/runner/work/pulumi/pulumi/pkg/backend/diy/state.go:128 +0xae\ngithub.com/pulumi/pulumi/pkg/v3/backend/diy.(*diyBackend).newUpdate(_, {_, _}, {_, _}, _, {0xc001fca370, {0xc001f98930, 0x1d}, {0x0, ...}, ...})\n\t/home/runner/work/pulumi/pulumi/pkg/backend/diy/state.go:101 +0xbd\ngithub.com/pulumi/pulumi/pkg/v3/backend/diy.(*diyBackend).apply(_, {_, _}, {_, _}, {_, _}, {0xc001fca370, {0xc001f98930, 0x1d}, ...}, ...)\n\t/home/runner/work/pulumi/pulumi/pkg/backend/diy/backend.go:1081 +0x2c5\ngithub.com/pulumi/pulumi/pkg/v3/backend.PreviewThenPromptThenExecute({_, _}, {_, _}, {_, _}, {0xc001fca370, {0xc001f98930, 0x1d}, {0x0, ...}, ...}, ...)\n\t/home/runner/work/pulumi/pulumi/pkg/backend/apply.go:272 +0x216\ngithub.com/pulumi/pulumi/pkg/v3/backend/diy.(*diyBackend).Update(_, {_, _}, {_, _}, {0xc001fca370, {0xc001f98930, 0x1d}, {0x0, 0x0, ...}, ...})\n\t/home/runner/work/pulumi/pulumi/pkg/backend/diy/backend.go:966 +0x1c5\ngithub.com/pulumi/pulumi/pkg/v3/backend.UpdateStack({_, _}, {_, _}, {0xc001fca370, {0xc001f98930, 0x1d}, {0x0, 0x0, 0x0}, ...})\n\t/home/runner/work/pulumi/pulumi/pkg/backend/stack.go:97 +0x9b\ngithub.com/pulumi/pulumi/pkg/v3/backend/diy.(*diyStack).Update(_, {_, _}, {0xc001fca370, {0xc001f98930, 0x1d}, {0x0, 0x0, 0x0}, 0xc00201c240, ...})\n\t/home/runner/work/pulumi/pulumi/pkg/backend/diy/stack.go:89 +0x68\nmain.newUpCmd.func1({_, _}, {_}, {_, _}, {_, _}, {{{0x6e8eda0, 0x0, 0x0}, ...}, ...}, ...)\n\t/home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/up.go:198 +0xeb6\nmain.newUpCmd.func3(0xc001fc0c08, {0xc001ffdc20, 0x0, 0x0?})\n\t/home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/up.go:574 +0xd09\nmain.newUpCmd.runCmdFunc.func4(0x0?, {0xc001ffdc20?, 0x0?, 0x0?})\n\t/home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/errors.go:45 +0x1c\nmain.newUpCmd.runCmdFunc.RunFunc.func7(0xc001fc0c08, {0xc001ffdc20, 0x0, 0xa})\n\t/home/runner/work/pulumi/pulumi/sdk/go/common/util/cmdutil/exit.go:99 +0x3b\ngithub.com/spf13/cobra.(*Command).execute(0xc001fc0c08, {0xc001ffdae0, 0xa, 0xa})\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:987 +0xa91\ngithub.com/spf13/cobra.(*Command).ExecuteC(0xc000f91b08)\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff\ngithub.com/spf13/cobra.(*Command).Execute(...)\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039\nmain.main()\n\t/home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/main.go:55 +0x4e\n\n\n"
```

tunnel.log
```
time=2024-11-14T23:32:35.131-05:00 level=ERROR msg="failed to execute command" command="[ifconfig utun69 destroy]" error="exit status 1"
```
[report.zip](https://github.com/user-attachments/files/17769672/report.zip)

**Comment by rijvirajib** [comment]
Small update here... When I run `npx sst dev` over and over again by seeing the Interrupt, closing it with Cntrl +C, and repeating, it seems to work without any code changes. 30% of the time successfully launches.

**Comment by jayair** [comment]
Which version of SST is this? And which OS was used for generating the report?

**Comment by jayair** [comment]
Another thing to check, are you running a tunnel? Is there a tunnel tab in `sst dev`?

**Comment by rijvirajib** [comment]
There is a tunnel. I am using SST 3.3.21. Node 22. 

The version above is from MacOS. Here's the Windows WSL one below:
```
time=2024-11-15T14:32:44.593-05:00 level=ERROR msg="pulumi error" line="================================================================================"
time=2024-11-15T14:32:44.593-05:00 level=ERROR msg="pulumi error" line="The Pulumi CLI encountered a fatal error. This is a bug!"
time=2024-11-15T14:32:44.593-05:00 level=ERROR msg="pulumi error" line="We would appreciate a report: https://github.com/pulumi/pulumi/issues/"
time=2024-11-15T14:32:44.593-05:00 level=ERROR msg="pulumi error" line="Please provide all of the text below in your report."
time=2024-11-15T14:32:44.593-05:00 level=ERROR msg="pulumi error" line="================================================================================"
time=2024-11-15T14:32:44.593-05:00 level=ERROR msg="pulumi error" line="Pulumi Version:   v3.136.1"
time=2024-11-15T14:32:44.593-05:00 level=ERROR msg="pulumi error" line="Go Version:       go1.23.2"
time=2024-11-15T14:32:44.593-05:00 level=ERROR msg="pulumi error" line="Go Compiler:      gc"
time=2024-11-15T14:32:44.593-05:00 level=ERROR msg="pulumi error" line="Architecture:     amd64"
time=2024-11-15T14:32:44.593-05:00 level=ERROR msg="pulumi error" line="Operating System: linux"
time=2024-11-15T14:32:44.593-05:00 level=ERROR msg="pulumi error" line="Panic:            runtime error: invalid memory address or nil pointer dereference"
time=2024-11-15T14:32:44.593-05:00 level=ERROR msg="pulumi error" line=""
time=2024-11-15T14:32:44.593-05:00 level=ERROR msg="pulumi error" line="goroutine 1 [running]:"
time=2024-11-15T14:32:44.593-05:00 level=ERROR msg="pulumi error" line=runtime/debug.Stack()
time=2024-11-15T14:32:44.593-05:00 level=ERROR msg="pulumi error" line="\t/opt/hostedtoolcache/go/1.23.2/x64/src/runtime/debug/stack.go:26 +0x5e"
time=2024-11-15T14:32:44.593-05:00 level=ERROR msg="pulumi error" line=main.panicHandler(0xc000f43f27)
time=2024-11-15T14:32:44.593-05:00 level=ERROR msg="pulumi error" line="\t/home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/main.go:34 +0x45"
time=2024-11-15T14:32:44.593-05:00 level=ERROR msg="pulumi error" line="panic({0x276e000?, 0x48fbc10?})"
time=2024-11-15T14:32:44.593-05:00 level=ERROR msg="pulumi error" line="\t/opt/hostedtoolcache/go/1.23.2/x64/src/runtime/panic.go:785 +0x132"
time=2024-11-15T14:32:44.593-05:00 level=ERROR msg="pulumi error" line="github.com/pulumi/pulumi/pkg/v3/backend/diy.(*diyBackend).getTarget(0xc000e11440, {0x3345c68, 0x49c1220}, {0x33216e0, 0x49c1220}, 0xc0011cf080, 0xc00128e780, {0x7fe0626551c0, 0x49c1220})"
time=2024-11-15T14:32:44.593-05:00 level=ERROR msg="pulumi error" line="\t/home/runner/work/pulumi/pulumi/pkg/backend/diy/state.go:128 +0xae"
time=2024-11-15T14:32:44.593-05:00 level=ERROR msg="pulumi error" line="github.com/pulumi/pulumi/pkg/v3/backend/diy.(*diyBackend).newUpdate(_, {_, _}, {_, _}, _, {0xc001dc1b80, {0xc001f24e40, 0x17}, {0x0, ...}, ...})"
time=2024-11-15T14:32:44.593-05:00 level=ERROR msg="pulumi error" line="\t/home/runner/work/pulumi/pulumi/pkg/backend/diy/state.go:101 +0xbd"
time=2024-11-15T14:32:44.593-05:00 level=ERROR msg="pulumi error" line="github.com/pulumi/pulumi/pkg/v3/backend/diy.(*diyBackend).apply(_, {_, _}, {_, _}, {_, _}, {0xc001dc1b80, {0xc001f24e40, 0x17}, ...}, ...)"
time=2024-11-15T14:32:44.593-05:00 level=ERROR msg="pulumi error" line="\t/home/runner/work/pulumi/pulumi/pkg/backend/diy/backend.go:1081 +0x2c5"
time=2024-11-15T14:32:44.593-05:00 level=ERROR msg="pulumi error" line="github.com/pulumi/pulumi/pkg/v3/backend.PreviewThenPromptThenExecute({_, _}, {_, _}, {_, _}, {0xc001dc1b80, {0xc001f24e40, 0x17}, {0x0, ...}, ...}, ...)"
time=2024-11-15T14:32:44.593-05:00 level=ERROR msg="pulumi error" line="\t/home/runner/work/pulumi/pulumi/pkg/backend/apply.go:272 +0x216"
time=2024-11-15T14:32:44.593-05:00 level=ERROR msg="pulumi error" line="github.com/pulumi/pulumi/pkg/v3/backend/diy.(*diyBackend).Update(_, {_, _}, {_, _}, {0xc001dc1b80, {0xc001f24e40, 0x17}, {0x0, 0x0, ...}, ...})"
time=2024-11-15T14:32:44.593-05:00 level=ERROR msg="pulumi error" line="\t/home/runner/work/pulumi/pulumi/pkg/backend/diy/backend.go:966 +0x1c5"
time=2024-11-15T14:32:44.593-05:00 level=ERROR msg="pulumi error" line="github.com/pulumi/pulumi/pkg/v3/backend.UpdateStack({_, _}, {_, _}, {0xc001dc1b80, {0xc001f24e40, 0x17}, {0x0, 0x0, 0x0}, ...})"
time=2024-11-15T14:32:44.593-05:00 level=ERROR msg="pulumi error" line="\t/home/runner/work/pulumi/pulumi/pkg/backend/stack.go:97 +0x9b"
time=2024-11-15T14:32:44.593-05:00 level=ERROR msg="pulumi error" line="github.com/pulumi/pulumi/pkg/v3/backend/diy.(*diyStack).Update(_, {_, _}, {0xc001dc1b80, {0xc001f24e40, 0x17}, {0x0, 0x0, 0x0}, 0xc000010bb8, ...})"
time=2024-11-15T14:32:44.593-05:00 level=ERROR msg="pulumi error" line="\t/home/runner/work/pulumi/pulumi/pkg/backend/diy/stack.go:89 +0x68"
time=2024-11-15T14:32:44.593-05:00 level=ERROR msg="pulumi error" line="main.newUpCmd.func1({_, _}, {_}, {_, _}, {_, _}, {{{0x49c1220, 0x0, 0x0}, ...}, ...}, ...)"
time=2024-11-15T14:32:44.593-05:00 level=ERROR msg="pulumi error" line="\t/home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/up.go:198 +0xeb6"
time=2024-11-15T14:32:44.593-05:00 level=ERROR msg="pulumi error" line="main.newUpCmd.func3(0xc000f6a308, {0xc0011d0000, 0x0, 0x0?})"
time=2024-11-15T14:32:44.593-05:00 level=ERROR msg="pulumi error" line="\t/home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/up.go:574 +0xd09"
time=2024-11-15T14:32:44.593-05:00 level=ERROR msg="pulumi error" line="main.newUpCmd.runCmdFunc.func4(0x0?, {0xc0011d0000?, 0x0?, 0x0?})"
time=2024-11-15T14:32:44.593-05:00 level=ERROR msg="pulumi error" line="\t/home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/errors.go:45 +0x1c"
time=2024-11-15T14:32:44.593-05:00 level=ERROR msg="pulumi error" line="main.newUpCmd.runCmdFunc.RunFunc.func7(0xc000f6a308, {0xc0011d0000, 0x0, 0xa})"
time=2024-11-15T14:32:44.593-05:00 level=ERROR msg="pulumi error" line="\t/home/runner/work/pulumi/pulumi/sdk/go/common/util/cmdutil/exit.go:99 +0x3b"
time=2024-11-15T14:32:44.593-05:00 level=ERROR msg="pulumi error" line="github.com/spf13/cobra.(*Command).execute(0xc000f6a308, {0xc0011c7e00, 0xa, 0xa})"
time=2024-11-15T14:32:44.593-05:00 level=ERROR msg="pulumi error" line="\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:987 +0xa91"
time=2024-11-15T14:32:44.593-05:00 level=ERROR msg="pulumi error" line=github.com/spf13/cobra.(*Command).ExecuteC(0xc001cbf208)
time=2024-11-15T14:32:44.593-05:00 level=ERROR msg="pulumi error" line="\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff"
time=2024-11-15T14:32:44.593-05:00 level=ERROR msg="pulumi error" line=github.com/spf13/cobra.(*Command).Execute(...)
time=2024-11-15T14:32:44.593-05:00 level=ERROR msg="pulumi error" line="\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039"
time=2024-11-15T14:32:44.593-05:00 level=ERROR msg="pulumi error" line=main.main()
time=2024-11-15T14:32:44.593-05:00 level=ERROR msg="pulumi error" line="\t/home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/main.go:55 +0x4e"
time=2024-11-15T14:32:44.593-05:00 level=ERROR msg="pulumi error" line=""
```

Tunnel looks like it's working on both mac and windows, looks like this:

![image](https://github.com/user-attachments/assets/effb5a1c-dd12-40b3-9632-dc710493cad7)

**Comment by rijvirajib** [comment]
Any progress on this? I keep having to `npx sst remove` and `npx sst dev` whenever I want to run things. Something on the VPC is not waiting? I dont know.

**Comment by rijvirajib** [comment]
Fixed it - when an SQS is first created, it pointed to a handler that didn't exist: `sqs.handlr` and not the correct path `sqs.handler`. It succeeds silently. The error shows up when the SQS is used on the first `sst dev` but subsequent `sst dev` fails because SQS is being interrupted, the handler doesn't exist.
