### ISSUE TITLE
Autodeploy Error: 'Buffer' is not assignable to parameter of type 'BinaryLike'.

### ISSUE THREAD

**Issue by abaybektursun** [anomalyco/sst#5093]
Full error stack
```
   ▲ Next.js 15.0.3
   Creating an optimized production build ...
 ✓ Compiled successfully
   Linting and checking validity of types ...
Failed to compile.
.sst/platform/src/components/aws/function.ts:1943:23
Type error: Argument of type 'Buffer' is not assignable to parameter of type 'BinaryLike'.
  Type 'Buffer' is not assignable to type 'Uint8Array | DataView'.
    Type 'Buffer' is not assignable to type 'Uint8Array'.
      The types returned by 'entries()' are incompatible between these types.
        Type 'IterableIterator<[number, number]>' is missing the following properties from type 'ArrayIterator<[number, number]>': map, filter, take, drop, and 9 more.
[0m [90m 1941 |[39m           [90m// Calculate hash of the zip file[39m[0m
[0m [90m 1942 |[39m           [36mconst[39m hash [33m=[39m crypto[33m.[39mcreateHash([32m"sha256"[39m)[33m;[39m[0m
[0m[31m[1m>[22m[39m[90m 1943 |[39m           hash[33m.[39mupdate([36mawait[39m fs[33m.[39mpromises[33m.[39mreadFile(zipPath))[33m;[39m[0m
[0m [90m      |[39m                       [31m[1m^[22m[39m[0m
[0m [90m 1944 |[39m           [36mconst[39m hashValue [33m=[39m hash[33m.[39mdigest([32m"hex"[39m)[33m;[39m[0m
[0m [90m 1945 |[39m           [36mconst[39m assetBucket [33m=[39m region[33m.[39mapply((region) [33m=>[39m[0m
[0m [90m 1946 |[39m             bootstrap[33m.[39mforRegion(region)[33m.[39mthen((d) [33m=>[39m d[33m.[39masset)[33m,[39m[0m
node:internal/errors:865
  const err = new Error(message);
              ^
Error: Command failed: npm run build
    at __node_internal_genericNodeError (node:internal/errors:865:15)
    at checkExecSyncError (node:child_process:890:11)
    at Object.execSync (node:child_process:962:15)
    at buildNextjsApp (file:///root/.npm/_npx/e014fccbbe7e583d/node_modules/@opennextjs/aws/dist/build.js:95:8)
    at build (file:///root/.npm/_npx/e014fccbbe7e583d/node_modules/@opennextjs/aws/dist/build.js:44:5)
    at async file:///root/.npm/_npx/e014fccbbe7e583d/node_modules/@opennextjs/aws/dist/index.js:9:1 {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 601,
  stdout: null,
  stderr: null
}
Node.js v18.20.3
|  Error       abay sst:aws:Nextjs → abayBuild sst:Run
|  command exited with code 1
✕  Failed    
   abay sst:aws:Nextjs → abayBuild sst:Run
   command exited with code 1
Error: Failed to run: /tmp/repo/application/node_modules/.bin/sst deploy --stage production
    at shell (file:///tmp/buildspec/index.mjs:238:13)
    at deploy (file:///tmp/buildspec/index.mjs:191:5)
    at workflow (file:///tmp/buildspec/index.mjs:161:59)
    at async runWorkflow (file:///tmp/buildspec/index.mjs:164:5)
    at async handler (file:///tmp/buildspec/index.mjs:48:5)
    at async file:///tmp/buildspec/[eval1]:1:122
```
Any pointers?
This happens both auto deploy and terminal deploy

**Comment by abaybektursun** [comment]
My bad, issue is gone after adding "sst.config.ts" back to tsconfig. Claude fucked it up when generating code.
```
"exclude": ["node_modules",  "sst.config.ts"]
```
