### ISSUE TITLE
Handle imports containing webassembly in sst.config.ts

### ISSUE THREAD

**Issue by bjorntechTobbe** [anomalyco/sst#5137]
I am trying to import credentials from 1password using the  "@1password/sdk”.

The reason for this is that we do store all credentials in 1password. This can be handled when running sst dev or sst deploy locally but using autodeploy it is not working.

Here is what I do:

Adding 

```
import { createClient } from "@1password/sdk";

// Creates an authenticated client.
const client = await createClient({
  auth: process.env.OP_SERVICE_ACCOUNT_TOKEN ?? (() => { throw new Error("OP_SERVICE_ACCOUNT_TOKEN is not set"); })(),
  integrationName: "My 1Password Integration",
  integrationVersion: "v1.0.0",
});

// Get a secret
const secret = await client.secrets.resolve("op://xxxx/xxx/xxxd");

```

in the top of sst.config.ts 

When running sst dev I get this error:

```
exited with error" err="Error evaluating config: exit status 1\nnode:fs:562\n  return binding.open(\n                 ^\n\nError: ENOENT: no such file or directory, open '/Users/xxxxx/Projects/op-test/.sst/platform/core_bg.wasm'\n    at Object.openSync (node:fs:562:18)\n    at Object.readFileSync (node:fs:446:35)\n    at node_modules/@1password/sdk-core/nodejs/core.js (file:///Users/xxxxx/Projects/op-test/.sst/platform/sst.config.1732694190550.mjs:651:33)\n    at __require2 (file:///Users/xxxxx/Projects/op-test/.sst/platform/sst.config.1732694190550.mjs:24:50)\n    at node_modules/@1password/sdk/dist/core.js (file:///Users/xxxxx/Projects/op-test/.sst/platform/sst.config.1732694190550.mjs:693:22)\n    at __require2 (file:///Users/xxxxx/Projects/op-test/.sst/platform/sst.config.1732694190550.mjs:24:50)\n    at node_modules/@1password/sdk/dist/sdk.js (file:///Users/xxxxx/Projects/op-test/.sst/platform/sst.config.1732694190550.mjs:1345:21)\n    at __require2 (file:///Users/xxxxx/Projects/op-test/.sst/platform/sst.config.1732694190550.mjs:24:50)\n    at file:///Users/xxxxx/Projects/op-test/.sst/platform/sst.config.1732694190550.mjs:1373:26\n    at ModuleJob.run (node:internal/modules/esm/module_job:271:25) {\n  errno: -2,\n  code: 'ENOENT',\n  syscall: 'open',\n  path: '/Users/xxxxx/Projects/op-test/.sst/platform/core_bg.wasm'\n}\n\nNode.js v23.2.0\n"

```

If I copy ”core_bg.wasm” and ”core_bg.wasm.d.ts” from node_modules/@1password/sdk-core/nodejs/ to .sst/platform it all works.

Would it be possible to add support for this?

**Comment by jayair** [comment]
Interesting. In general imports within the sst config are a little restrictive because of the internal dir structure.

> This can be handled when running sst dev or sst deploy

You mean it can be handled because of the workaround of copying it to the right directory?

It's also weird that it's looking for the files in `.sst/platform` any idea why?

I'm also curious about the credentials you are storing in there. Which ones are these? Can you show me how you use them in your sst config?

**Comment by bjorntechTobbe** [comment]
The credentials are for AWS and Cloudflare. By storing them in OnePassword, we can easily share them between developers and projects while maintaining high security. Locally, they are unlocked with a fingerprint, and in GitHub actions, we only need to store one token to unlock all credentials.

Currently, we handle all stages by running a shell before starting, but we would prefer to include the handling in the sst config and be able to use sst auto-deploy.

The shell looks like this 



```

#!/usr/bin/env bun

console.log("Starting sst.ts");

import { OnePassword } from '@xxxxx/onepassword';
import { $ } from 'bun';

// Initialize OnePassword client
const op = new OnePassword();

// Function to read from 1Password
async function readFromOp(ref: string): Promise<string> {
  try {
    return await op.getSecret(ref);
  } catch (error) {
    console.error(`Error reading from 1Password: ${error instanceof Error ? error.message : String(error)}`);
    return '';
  }
}

async function main() {
  try {
    // Read and parse the JSON environment file
    const envConfig = JSON.parse(await Bun.file('./shells/env.json').text());
    
    // Get the stage from command line arguments
    const sstArgs = process.argv.slice(2);
    const stageIndex = sstArgs.indexOf('--stage');
    const stage = String(stageIndex !== -1 && stageIndex + 1 < sstArgs.length ? sstArgs[stageIndex + 1] : process.env.USER);

    if (stage !== '') {
      console.log(`Using stage: ${stage}`);
    }

    // Check if running in GitHub Actions and abort for specific stages
    if (process.env.GITHUB_ACTIONS !== 'true' && ['production', 'development', 'staging'].includes(stage)) {
      console.error(`Aborting: Cannot run stage '${stage}' outside GitHub Actions environment.`);
      return;
    }

    // Use stage-specific variables if available, otherwise use default
    const configToUse = envConfig[stage] || envConfig.default;

    // Add variables from the "always" section
    const alwaysConfig = envConfig.always || {};

    // Combine stage-specific (or default) config with "always" config
    const combinedConfig = { ...alwaysConfig, ...configToUse };

    // Read all secrets from 1Password and set environment variables
    const envPromises = Object.entries(combinedConfig).map(async ([key, value]) => {
      const secret = await readFromOp(value as string);
      return [key, secret];
    });

    const envSecrets = Object.fromEntries(await Promise.all(envPromises));
    
    // Add existing environment variables
    for (const [key, value] of Object.entries(process.env)) {
      envSecrets[key] = value;
    }

    $.env(envSecrets);

    // Execute SST command with environment variables
    const { stdout, stderr } = await $`sst $(echo ${sstArgs.join(' ')})`;
    
    console.log(stdout.toString());

    if (stderr) {
      console.error(stderr.toString());
    }

  } catch (error) {
    console.error(`Error in main execution: ${error instanceof Error ? error.message : String(error)}`);
  }
}

main();

```

and the config file like this 

```
{
  "tobbe": {
    "AWS_ACCESS_KEY_ID": "op://fdsagrasgdsfat45/fvdsfdst43t4/aws-access-key-id",
    "AWS_SECRET_ACCESS_KEY": "op://fdsagrasgdsfat45/fvdsfdst43t4/aws-secret-access-key"
  },
  "development": {
    "AWS_ACCESS_KEY_ID": "op://fdsagrasgdsfat45/fvdsfdst43t4/aws-access-key-id",
    "AWS_SECRET_ACCESS_KEY": "op://fdsagrasgdsfat45/fvdsfdst43t4/aws-secret-access-key"
  },
  "production": {
    "AWS_ACCESS_KEY_ID": "op://fdsagrasgdsfat45/fvdsfdst43t4/aws-access-key-id",
    "AWS_SECRET_ACCESS_KEY": "op://fdsagrasgdsfat45/fvdsfdst43t4/aws-secret-access-key"
  },
  "always": {
    "CLOUDFLARE_API_TOKEN": "op://fdsagrasgdsfat45/fdstgfsdgter6534/credential",
    "CLOUDFLARE_DEFAULT_ACCOUNT_ID": "op://fdsagrasgdsfat45/fdsgrwre54/account-id",
    "OP_SERVICE_ACCOUNT_TOKEN": "op://fdsagrasgdsfat45/xbm36lduf5opaiysc746itfiiq/credential"
  }
}
```

**Comment by bjorntechTobbe** [comment]
And, sorry...I did not answer your question on why it is looking for the files in ".sst/platform". I guessed it was because of your packing process, but I have no clue.

**Comment by thdxr** [comment]
i looked into this - the simplest thing is to add dependencies with binary deps to `nodejs.install = ["mydep"]` on the function<br><br>there's some sketchy approaches to inlining WASM into a js bundle but feels like it's more trouble than it's worth

**Comment by luizkc** [comment]
@thdxr what if I'm not calling the package from a function? I'm trying to import it in one of my `infra` files and I have the package installed in the root `package.json` of my monorepo.
