### ISSUE TITLE
Error: $config is not defined

### ISSUE THREAD

**Issue by rupertlssmith** [anomalyco/sst#5166]
Everything was working fine, but I did have a build error on a StaticSite, which I rolled back. After that I get the 'Error: $config is not defined' message. I suspect something in the .sst folder might have gotten corrupted?

> npx sst dev

Error: $config is not defined

Trace: ReferenceError: $config is not defined
    at file:///home/rupert/sc/gitlab/elm-realtime/.sst.config.1733227067471.mjs:4:26
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
    at process.<anonymous> (file:///home/rupert/.npm/_npx/35e81a5509205fcc/node_modules/sst/cli/sst.js:58:21)
    at process.emit (node:events:525:35)
    at process.emit (node:domain:489:12)
    at process._fatalException (node:internal/process/execution:149:25)
    at processPromiseRejections (node:internal/process/promises:288:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)

===

Possibly related to: https://github.com/sst/sst/issues/4458

**Comment by rupertlssmith** [comment]
Weirdly removing .sst folder did not cure the problem.

I had to remove node_module and reinstall them to fix it??

**Comment by jayair** [comment]
It seems like you were somehow running sst v2. Closing for now.

**Comment by rupertlssmith** [comment]
Could be a versioning issue, somehow npm installed v2 perhaps. Certianly removing node_modules and re-running `npm install` fixed it.
