### ISSUE TITLE
panic: semaphore: released more than held

### ISSUE THREAD

**Issue by rupertlssmith** [anomalyco/sst#5173]
rupert@snake:~/sc/gitlab/elm-realtime$ npx sst dev
panic: semaphore: released more than held

goroutine 180 [running]:
golang.org/x/sync/semaphore.(*Weighted).Release(0xc0000c08c0, 0xc0080d2fc8?)
        /home/runner/go/pkg/mod/golang.org/x/sync@v0.8.0/semaphore/semaphore.go:127 +0xb8
github.com/sst/ion/pkg/runtime/node.(*Runtime).Build(0xc0001d88a0, {0x33fe0b0?, 0xc000999e00?}, 0xc001e68320)
        /home/runner/work/sst/sst/pkg/runtime/node/build.go:292 +0x194a
github.com/sst/ion/pkg/runtime.(*Collection).Build(0xc00014c420, {0x33fe0b0, 0xc000999e00}, 0xc001e68320)
        /home/runner/work/sst/sst/pkg/runtime/runtime.go:120 +0x45f
github.com/sst/ion/cmd/sst/mosaic/aws.Start.func1.1({0xc0005a36a0, 0x1c})
        /home/runner/work/sst/sst/cmd/sst/mosaic/aws/aws.go:134 +0xb5
github.com/sst/ion/cmd/sst/mosaic/aws.Start.func1()
        /home/runner/work/sst/sst/cmd/sst/mosaic/aws/aws.go:345 +0x1d54
created by github.com/sst/ion/cmd/sst/mosaic/aws.Start in goroutine 80
        /home/runner/work/sst/sst/cmd/sst/mosaic/aws/aws.go:121 +0x6b5

golang was not happy with its semaphores, I have no idea why. Logged the stack trace anyway.

$ npx sst version
sst 3.3.12

**Comment by jayair** [comment]
Can you share some more details on how to reproduce this?

**Comment by paolostyle** [comment]
Not super helpful but I'm sometimes getting these in the console when Ctrl+C-ing `sst dev`. It doesn't really break anything, though.

**Comment by rupertlssmith** [comment]
I don't know how to reproduce its a non-deterministic error unfortunately.
