### ISSUE TITLE
React Router 7

### ISSUE THREAD

**Issue by cwagner22** [anomalyco/sst#5188]
Since Remix is now React Router 7, is there any way to use sst to deploy a React Router app? (to Lambda)

I added `@remix-run/node` as dependency in case it'd work but getting:
```
TypeError: (0 , import_server.renderToReadableStream) is not a function
````

I also tried to add hono server:
```
ERROR	Invoke Error 	{"errorType":"TypeError","errorMessage":"Cannot convert undefined or null to object",
"stack":["TypeError: Cannot convert undefined or null to object","  
at Function.values (<anonymous>)","    
at groupRoutesByParentId (file:///var/task/bundle.mjs:30373:10)","
at createRoutes (file:///var/task/bundle.mjs:30382:67)","    at derive (file:///var/task/bundle.mjs:30522:16)","    at requestHandler (file:///var/task/bundle.mjs:30853:25)","    at Runtime.handler (file:///var/task/bundle.mjs:31964:28)","    at Runtime.handleOnceStreaming (file:///var/runtime/index.mjs:1199:38)"]}
```

By the way it gets stuck on  `Updating    MyWeb sst:aws:Remix → MyWebAssetFiles sst:aws:BucketFiles` for almost 10 minutes just for a few files, not sure if normal.

**Comment by ironheart122** [comment]
Oh damn. Have you figured out a workaround to this bug?

**Comment by Paliago** [comment]
This works:
https://github.com/sst/sst/pull/5159

**Comment by cwagner22** [comment]
Thanks, closing even though I have no idea how to deploy to Lambda@Edge due to `Resource linking is not currently supported when deploying to the edge.`
