### ISSUE TITLE
500 on missing AUTH_PUBLIC_KEY using sst.aws.Auth

### ISSUE THREAD

**Issue by klcodanr** [anomalyco/sst#5234]
~~~
SST v3.4.18
Node.js v20.10.0
~~~

I'm trying to use `sst.aws.Auth` with a `LinkAdapter` and when I try to call the auth endpoint I get a 500 and the following error:

```
|  Invoke      packages/functions/src/auth.handler
|  +24ms       Error: "AUTH_PUBLIC_KEY" is not linked in your sst.config.ts to thecaringplace-info-klco-AuthAuthorizerFunction
|  +24ms           at Object.get (/Users/klco/git/thecaringplace-info/node_modules/sst/dist/resource.js:83:15)
|  +24ms           at Object.publicKey (/Users/klco/git/thecaringplace-info/node_modules/sst/dist/auth/handler.js:60:53)
|  +24ms           at handler (/Users/klco/git/thecaringplace-info/node_modules/sst/dist/auth/adapter/link.js:22:71)
```

I tried linking a secret `AUTH_PUBLIC_KEY` to the Auth function and then I still got a 500 and a cryptic error.

I updated the code in my `node_modules` to get `jose` to dump the value of the key and saw:

```
|  +9ms        authorize request for link
|  +30ms       TypeError: {"value":"-----BEGIN PRIVATE KEY-----\nAN_ACTUAL_KEY\n-----END PRIVATE KEY-----\n","type":"sst:sst:Secret"} must be P
KCS#8 formatted string
|  +30ms           at importPKCS8 (/Users/klco/git/thecaringplace-info/node_modules/jose/dist/node/esm/key/import.js:20:15)
```

The documentation on auth is pretty thin, but I _assume_ that the private and public keys are supposed to be secrets. Am I wrong about this?

**Comment by thdxr** [comment]
this component has been updated
