### ISSUE TITLE
Issue with build command override when running "sst deploy"

### ISSUE THREAD

**Issue by marko-spanovic-ananas** [anomalyco/sst#5260]
My sst.config.ts:

```
/// <reference path="./.sst/platform/config.d.ts" />
const environments = ["production", "development", "staging", "qa", "qa2"]; 

export default $config({
  app(input) {
    return {
      name: "ananas-new-customer-app ",
      removal: environments.includes(input?.stage) ? "retain" : "remove",
      protect: environments.includes(input?.stage),
      region: "eu-central-1",
      home: "aws",
      edge: false
    };
  },
  async run() {
    new sst.aws.Nextjs("MyWeb", {
      domain: {
        name: String(process.env.OPENNEXT_NEW_PUBLIC_APP_DOMAIN_NAME),
        dns: sst.aws.dns({zone: process.env.OPENNEXT_NEW_PUBLIC_APP_DOMAIN_ZONE_ID }),
        redirects: ["www." + process.env.OPENNEXT_NEW_PUBLIC_APP_DOMAIN_NAME],
      },
      //TODO There seems that there is some issue with the buildCommand where anything except first build is failing 
      // buildCommand: "npm run build:" + process.env.NEXT_PUBLIC_ENVIRONMENT
    });
  },
});
```

When I uncomment buildCommand first deploy is successful, but if I clear temp files or try to run in on another machine all subsequent deploys are failing. We are getting this error:

```
time=2024-12-25T12:42:16.526Z level=INFO msg="done running stack command"

✕  Failed    
   Failed to load open-next.output.json from ".open-next/open-next.output.json".


time=2024-12-25T12:42:16.529Z level=INFO msg="INFO unlocking app=ananas-new-customer-app stage=development"
time=2024-12-25T12:42:16.847Z level=INFO msg="shutting down server"
time=2024-12-25T12:42:16.847Z level=INFO msg="server done"
time=2024-12-25T12:42:16.847Z level=ERROR msg="exited with error" err="failed to run update: exit status 255\ncode: 255\nstdout: Updating (development):\nDownloading plugin vercel-1.11.0: starting\nDownloading plugin cloudflare-5.37.1: starting\nDownloading plugin docker-build-0.0.6: starting\nDownloading plugin vercel-1.11.0: done\nDownloading plugin tls-5.0.1: starting\nInstalling plugin vercel-1.11.0: starting\nDownloading plugin tls-5.0.1: done\nInstalling plugin tls-5.0.1: starting\nDownloading plugin cloudflare-5.37.1: done\nInstalling plugin vercel-1.11.0: done\nDownloading plugin docker-build-0.0.6: done\nInstalling plugin cloudflare-5.37.1: starting\n@ updating....\nInstalling plugin docker-build-0.0.6: starting\nInstalling plugin tls-5.0.1: done\n@ updating....\nInstalling plugin cloudflare-5.37.1: done\nInstalling plugin docker-build-0.0.6: done\n\n    pulumi:pulumi:Stack ananas-new-customer-app-development running \n@ updating......\n ~  pulumi-nodejs:dynamic:Resource MyWebBuild.sst.Run updating (0s) [diff: ~env,version]\n@ updating.............................................................\n ~  pulumi-nodejs:dynamic:Resource MyWebBuild.sst.Run updated (57s) [diff: ~env,version]\n    pulumi:pulumi:Stack ananas-new-customer-app-development running error: Running program '/home/runner/work/ananas-new-customer-app/ananas-new-customer-app/.sst/platform/sst.config.1735130467854.mjs' failed with an unhandled exception:\n    pulumi:pulumi:Stack ananas-new-customer-app-development **failed** 1 error\nDiagnostics:\n  pulumi:pulumi:Stack (ananas-new-customer-app-development):\n    error: Running program '/home/runner/work/ananas-new-customer-app/ananas-new-customer-app/.sst/platform/sst.config.1735130467854.mjs' failed with an unhandled exception:\n    \x1b[36m<ref *1>\x1b[39m VisibleError: Failed to load open-next.output.json from \".open-next/open-next.output.json\".\n        at \x1b[90mfile:///home/runner/work/ananas-new-customer-app/ananas-new-customer-app/\x1b[39m.sst/platform/src/components/aws/nextjs.ts:618:17\n        at \x1b[90m/home/runner/work/ananas-new-customer-app/ananas-new-customer-app/\x1b[39m.sst/platform/node_modules/\x1b[4m@pulumi\x1b[24m/output.ts:490:31\n        at Generator.next (<anonymous>)\n        at \x1b[90m/home/runner/work/ananas-new-customer-app/ananas-new-customer-app/\x1b[39m.sst/platform/node_modules/\x1b[4m@pulumi\x1b[24m/pulumi/output.js:21:71\n        at new Promise (<anonymous>)\n        at __awaiter \x1b[90m(/home/runner/work/ananas-new-customer-app/ananas-new-customer-app/\x1b[39m.sst/platform/node_modules/\x1b[4m@pulumi\x1b[24m/pulumi/output.js:17:12\x1b[90m)\x1b[39m\n        at applyHelperAsync \x1b[90m(/home/runner/work/ananas-new-customer-app/ananas-new-customer-app/\x1b[39m.sst/platform/node_modules/\x1b[4m@pulumi\x1b[24m/pulumi/output.js:298:12\x1b[90m)\x1b[39m\n        at \x1b[90m/home/runner/work/ananas-new-customer-app/ananas-new-customer-app/\x1b[39m.sst/platform/node_modules/\x1b[4m@pulumi\x1b[24m/output.ts:352:13\n    \x1b[90m    at processTicksAndRejections (node:internal/process/task_queues:95:5)\x1b[39m {\n      promise: Promise { \x1b[36m<rejected>\x1b[39m \x1b[36m[Circular *1]\x1b[39m }\n    }\n\nOutputs:\n    _protect: true\n\nResources:\n    ~ 1 updated\n    10 unchanged\n\nDuration: 1m1s\n\n\nstderr: \n"
✕  Unexpected error occurred. Please run with --print-logs or check .sst/log/sst.log if available.
```

**Comment by jayair** [comment]
So this is the error `Failed to load open-next.output.json from \".open-next/open-next.output.json\"`

It sounds like your build command is not running the OpenNext build?

**Comment by marko-spanovic-ananas** [comment]
Hi, so I'm running "npx sst deploy --stage development", and If you print whole error with "--print-logs" arg this is whole log.

`time=2024-12-25T12:42:16.847Z level=ERROR msg="exited with error" err="failed to run update: exit status 255\ncode: 255\nstdout: Updating (development):\nDownloading plugin vercel-1.11.0: starting\nDownloading plugin cloudflare-5.37.1: starting\nDownloading plugin docker-build-0.0.6: starting\nDownloading plugin vercel-1.11.0: done\nDownloading plugin tls-5.0.1: starting\nInstalling plugin vercel-1.11.0: starting\nDownloading plugin tls-5.0.1: done\nInstalling plugin tls-5.0.1: starting\nDownloading plugin cloudflare-5.37.1: done\nInstalling plugin vercel-1.11.0: done\nDownloading plugin docker-build-0.0.6: done\nInstalling plugin cloudflare-5.37.1: starting\n@ updating....\nInstalling plugin docker-build-0.0.6: starting\nInstalling plugin tls-5.0.1: done\n@ updating....\nInstalling plugin cloudflare-5.37.1: done\nInstalling plugin docker-build-0.0.6: done\n\n    pulumi:pulumi:Stack ananas-new-customer-app-development running \n@ updating......\n ~  pulumi-nodejs:dynamic:Resource MyWebBuild.sst.Run updating (0s) [diff: ~env,version]\n@ updating.............................................................\n ~  pulumi-nodejs:dynamic:Resource MyWebBuild.sst.Run updated (57s) [diff: ~env,version]\n    pulumi:pulumi:Stack ananas-new-customer-app-development running error: Running program '/home/runner/work/ananas-new-customer-app/ananas-new-customer-app/.sst/platform/sst.config.1735130467854.mjs' failed with an unhandled exception:\n    pulumi:pulumi:Stack ananas-new-customer-app-development **failed** 1 error\nDiagnostics:\n  pulumi:pulumi:Stack (ananas-new-customer-app-development):\n    error: Running program '/home/runner/work/ananas-new-customer-app/ananas-new-customer-app/.sst/platform/sst.config.1735130467854.mjs' failed with an unhandled exception:\n    \x1b[36m<ref *1>\x1b[39m VisibleError: Failed to load open-next.output.json from \".open-next/open-next.output.json\".\n        at \x1b[90mfile:///home/runner/work/ananas-new-customer-app/ananas-new-customer-app/\x1b[39m.sst/platform/src/components/aws/nextjs.ts:618:17\n        at \x1b[90m/home/runner/work/ananas-new-customer-app/ananas-new-customer-app/\x1b[39m.sst/platform/node_modules/\x1b[4m@pulumi\x1b[24m/output.ts:490:31\n        at Generator.next (<anonymous>)\n        at \x1b[90m/home/runner/work/ananas-new-customer-app/ananas-new-customer-app/\x1b[39m.sst/platform/node_modules/\x1b[4m@pulumi\x1b[24m/pulumi/output.js:21:71\n        at new Promise (<anonymous>)\n        at __awaiter \x1b[90m(/home/runner/work/ananas-new-customer-app/ananas-new-customer-app/\x1b[39m.sst/platform/node_modules/\x1b[4m@pulumi\x1b[24m/pulumi/output.js:17:12\x1b[90m)\x1b[39m\n        at applyHelperAsync \x1b[90m(/home/runner/work/ananas-new-customer-app/ananas-new-customer-app/\x1b[39m.sst/platform/node_modules/\x1b[4m@pulumi\x1b[24m/pulumi/output.js:298:12\x1b[90m)\x1b[39m\n        at \x1b[90m/home/runner/work/ananas-new-customer-app/ananas-new-customer-app/\x1b[39m.sst/platform/node_modules/\x1b[4m@pulumi\x1b[24m/output.ts:352:13\n    \x1b[90m    at processTicksAndRejections (node:internal/process/task_queues:95:5)\x1b[39m {\n      promise: Promise { \x1b[36m<rejected>\x1b[39m \x1b[36m[Circular *1]\x1b[39m }\n    }\n\nOutputs:\n    _protect: true\n\nResources:\n    ~ 1 updated\n    10 unchanged\n\nDuration: 1m1s\n\n\nstderr: \n"`

My wild guess is that there is some circular dependency that is stored locally and without this Generator fails.

**Comment by jayair** [comment]
Let me double check, are you setting the `buildCommand` in your component when you are running this?

**Comment by mcfry** [comment]
Not OP but that's what I was doing when I got the same error - I guess I expected `npx --yes open-next@OPEN_NEXT_VERSION build` to be run automatically after whatever I specified

**Comment by jayair** [comment]
@mcfry can you share your sst config for the Next.js component?
