### ISSUE TITLE
`b.Va is not a function` error from a surprising cause

### ISSUE THREAD

**Issue by dror-weiss** [anomalyco/sst#5266]
I was trying to create a resource in AWS and got the following error:

```
|  Error: Request message serialization failure: b.Va is not a function
|      at Object.callback (/path/to/api/.sst/platform/node_modules/@pulumi/runtime/invoke.ts:285:37)
|      at Object.onReceiveStatus (/path/to/api/.sst/platform/node_modules/@grpc/grpc-js/src/client.ts:360:26)
|      at Object.onReceiveStatus (/path/to/api/.sst/platform/node_modules/@grpc/grpc-js/src/client-interceptors.ts:458:34)
|      at Object.onReceiveStatus (/path/to/api/.sst/platform/node_modules/@grpc/grpc-js/src/client-interceptors.ts:419:48)
|      at /path/to/api/.sst/platform/node_modules/@grpc/grpc-js/src/resolving-call.ts:132:24
|      at processTicksAndRejections (node:internal/process/task_queues:77:11) {
|    promise: Promise { <rejected> [Circular *1] }
|  }
|  Error
```

Turns out, I was importing code with GCP, although the provider being declared and used was only AWS. Commenting out the GCP import or installing GCP provider removes the error.

I have no idea how to better communicate this, but I hope this issue will be resolved in the future.

**Comment by jayair** [comment]
Can you share the part of your config that was causing this?

**Comment by thdxr** [comment]
closing for now let us know if you still run into this
